export default [
  { label: 'ADHD Screening', value: 'ADHD Screening' },
  {
    label: 'Adrenocorticotropic Hormone (ACTH)',
    value: 'Adrenocorticotropic Hormone (ACTH)',
  },
  { label: 'Albumin Blood Test', value: 'Albumin Blood Test' },
  { label: 'Aldosterone Test', value: 'Aldosterone Test' },
  { label: 'Alkaline Phosphatase', value: 'Alkaline Phosphatase' },
  { label: 'Allergy Blood Test', value: 'Allergy Blood Test' },
  {
    label: 'Alpha Fetoprotein (AFP) Tumor Marker Test',
    value: 'Alpha Fetoprotein (AFP) Tumor Marker Test',
  },
  {
    label: 'Alpha-Fetoprotein (AFP) Test',
    value: 'Alpha-Fetoprotein (AFP) Test',
  },
  { label: 'ALT Blood Test', value: 'ALT Blood Test' },
  { label: 'Ammonia Levels', value: 'Ammonia Levels' },
  { label: 'Amylase Test', value: 'Amylase Test' },
  {
    label: 'ANA (Antinuclear Antibody) Test',
    value: 'ANA (Antinuclear Antibody) Test',
  },
  { label: 'Anion Gap Blood Test', value: 'Anion Gap Blood Test' },
  {
    label: 'Anti-Müllerian Hormone Test',
    value: 'Anti-Müllerian Hormone Test',
  },
  { label: 'Appendicitis Tests', value: 'Appendicitis Tests' },
  {
    label: 'Antineutrophil Cytoplasmic Antibodies (ANCA) Test',
    value: 'Antineutrophil Cytoplasmic Antibodies (ANCA) Test',
  },
  { label: 'Bacteria Culture Test', value: 'Bacteria Culture Test' },
  { label: 'AST Test', value: 'AST Test' },
  { label: 'Balance Tests', value: 'Balance Tests' },
  { label: 'Bacterial Vaginosis Test', value: 'Bacterial Vaginosis Test' },
  {
    label: 'Beta 2 Microglobulin (B2M) Tumor Marker Test',
    value: 'Beta 2 Microglobulin (B2M) Tumor Marker Test',
  },
  { label: 'BCR ABL Genetic Test', value: 'BCR ABL Genetic Test' },
  { label: 'Bilirubin in Urine', value: 'Bilirubin in Urine' },
  { label: 'Bilirubin Blood Test', value: 'Bilirubin Blood Test' },
  { label: 'Blood Differential', value: 'Blood Differential' },
  { label: 'Blood Alcohol Level', value: 'Blood Alcohol Level' },
  { label: 'Blood in Urine', value: 'Blood in Urine' },
  { label: 'Blood Glucose Test', value: 'Blood Glucose Test' },
  { label: 'Blood Smear', value: 'Blood Smear' },
  { label: 'Blood Oxygen Level', value: 'Blood Oxygen Level' },
  { label: 'BRAF Genetic Test', value: 'BRAF Genetic Test' },
  { label: 'Bone Marrow Tests', value: 'Bone Marrow Tests' },
  { label: 'Breast Biopsy', value: 'Breast Biopsy' },
  { label: 'BRCA Test', value: 'BRCA Test' },
  { label: 'Burn Evaluation', value: 'Burn Evaluation' },
  { label: 'BUN (Blood Urea Nitrogen)', value: 'BUN (Blood Urea Nitrogen)' },
  {
    label: 'C-Reactive Protein (CRP) Test',
    value: 'C-Reactive Protein (CRP) Test',
  },
  { label: 'C-Peptide Test', value: 'C-Peptide Test' },
  {
    label: 'CA 19-9 Blood Test (Pancreatic Cancer)',
    value: 'CA 19-9 Blood Test (Pancreatic Cancer)',
  },
  { label: 'C. Diff Testing', value: 'C. Diff Testing' },
  { label: 'Calcitonin Test', value: 'Calcitonin Test' },
  {
    label: 'CA-125 Blood Test (Ovarian Cancer)',
    value: 'CA-125 Blood Test (Ovarian Cancer)',
  },
  { label: 'Calcium in Urine Test', value: 'Calcium in Urine Test' },
  { label: 'Calcium Blood Test', value: 'Calcium Blood Test' },
  { label: 'CD4 Lymphocyte Count', value: 'CD4 Lymphocyte Count' },
  {
    label: 'Carbon Dioxide (CO2) in Blood',
    value: 'Carbon Dioxide (CO2) in Blood',
  },
  { label: 'Celiac Disease Screening', value: 'Celiac Disease Screening' },
  { label: 'CEA Test', value: 'CEA Test' },
  { label: 'Ceruloplasmin Test', value: 'Ceruloplasmin Test' },
  {
    label: 'Cerebrospinal Fluid (CSF) Analysis',
    value: 'Cerebrospinal Fluid (CSF) Analysis',
  },
  { label: 'Chloride Blood Test', value: 'Chloride Blood Test' },
  { label: 'Chlamydia Test', value: 'Chlamydia Test' },
  { label: 'Coagulation Factor Tests', value: 'Coagulation Factor Tests' },
  { label: 'Cholesterol Levels', value: 'Cholesterol Levels' },
  { label: 'Complete Blood Count (CBC)', value: 'Complete Blood Count (CBC)' },
  { label: 'Cognitive Testing', value: 'Cognitive Testing' },
  { label: 'Concussion Tests', value: 'Concussion Tests' },
  {
    label: 'Comprehensive Metabolic Panel (CMP)',
    value: 'Comprehensive Metabolic Panel (CMP)',
  },
  { label: 'Cortisol Test', value: 'Cortisol Test' },
  {
    label: 'Cord Blood Testing and Banking',
    value: 'Cord Blood Testing and Banking',
  },
  { label: 'Creatinine Test', value: 'Creatinine Test' },
  { label: 'Creatine Kinase', value: 'Creatine Kinase' },
  {
    label: 'CSF Immunoglobulin G (IgG) Index',
    value: 'CSF Immunoglobulin G (IgG) Index',
  },
  { label: 'Crystals in Urine', value: 'Crystals in Urine' },
  { label: 'Dental Exam', value: 'Dental Exam' },
  { label: 'Dengue Fever Test', value: 'Dengue Fever Test' },
  { label: 'Diabetic Foot Exam', value: 'Diabetic Foot Exam' },
  { label: 'Depression Screening', value: 'Depression Screening' },
  { label: 'Doppler Ultrasound', value: 'Doppler Ultrasound' },
  { label: 'Differential Diagnosis', value: 'Differential Diagnosis' },
  { label: 'Drug Testing', value: 'Drug Testing' },
  { label: 'Down Syndrome Tests', value: 'Down Syndrome Tests' },
  { label: 'Electrocardiogram', value: 'Electrocardiogram' },
  { label: 'Elastography', value: 'Elastography' },
  {
    label: 'Erythrocyte Sedimentation Rate (ESR)',
    value: 'Erythrocyte Sedimentation Rate (ESR)',
  },
  { label: 'Epithelial Cells in Urine', value: 'Epithelial Cells in Urine' },
  { label: 'Fasting for a Blood Test', value: 'Fasting for a Blood Test' },
  { label: 'Estrogen Levels Test', value: 'Estrogen Levels Test' },
  { label: 'Ferritin Blood Test', value: 'Ferritin Blood Test' },
  {
    label: 'Fecal Occult Blood Test (FOBT)',
    value: 'Fecal Occult Blood Test (FOBT)',
  },
  {
    label: 'Follicle-Stimulating Hormone (FSH) Levels Test',
    value: 'Follicle-Stimulating Hormone (FSH) Levels Test',
  },
  { label: 'Flu (Influenza) Test', value: 'Flu (Influenza) Test' },
  { label: 'Fungal Culture Test', value: 'Fungal Culture Test' },
  { label: 'Food Allergy Testing', value: 'Food Allergy Testing' },
  { label: 'Globulin Test', value: 'Globulin Test' },
  { label: 'Glaucoma Tests', value: 'Glaucoma Tests' },
  { label: 'Glucose in Urine Test', value: 'Glucose in Urine Test' },
  {
    label: 'Glomerular Filtration Rate (GFR) Test',
    value: 'Glomerular Filtration Rate (GFR) Test',
  },
  { label: 'Hearing Tests for Adults', value: 'Hearing Tests for Adults' },
  { label: 'Gonorrhea Test', value: 'Gonorrhea Test' },
  { label: 'Heavy Metal Blood Test', value: 'Heavy Metal Blood Test' },
  { label: 'Hearing Tests for Children', value: 'Hearing Tests for Children' },
  { label: 'Hematocrit Test', value: 'Hematocrit Test' },
  {
    label: 'Helicobacter Pylori (H. Pylori) Tests',
    value: 'Helicobacter Pylori (H. Pylori) Tests',
  },
  { label: 'Hemoglobin Test', value: 'Hemoglobin Test' },
  {
    label: 'Hemoglobin A1C (HbA1c) Test',
    value: 'Hemoglobin A1C (HbA1c) Test',
  },
  {
    label: 'HER2 (Breast Cancer) Testing',
    value: 'HER2 (Breast Cancer) Testing',
  },
  { label: 'Hepatitis Panel', value: 'Hepatitis Panel' },
  { label: 'HIV Screening Test', value: 'HIV Screening Test' },
  { label: 'Herpes (HSV) Test', value: 'Herpes (HSV) Test' },
  { label: 'Homocysteine Test', value: 'Homocysteine Test' },
  { label: 'HIV Viral Load', value: 'HIV Viral Load' },
  {
    label: 'Human Papillomavirus (HPV) Test',
    value: 'Human Papillomavirus (HPV) Test',
  },
  {
    label: 'How to Understand Your Lab Results',
    value: 'How to Understand Your Lab Results',
  },
  { label: 'Insulin in Blood', value: 'Insulin in Blood' },
  { label: 'Immunoglobulins Blood Test', value: 'Immunoglobulins Blood Test' },
  { label: 'Karyotype Genetic Test', value: 'Karyotype Genetic Test' },
  {
    label: 'Intravenous Pyelogram (IVP)',
    value: 'Intravenous Pyelogram (IVP)',
  },
  { label: 'Ketones in Urine', value: 'Ketones in Urine' },
  { label: 'Ketones in Blood', value: 'Ketones in Blood' },
  {
    label: 'Lactate Dehydrogenase (LDH) Isoenzymes Test',
    value: 'Lactate Dehydrogenase (LDH) Isoenzymes Test',
  },
  { label: 'Kidney Stone Analysis', value: 'Kidney Stone Analysis' },
  { label: 'Lactic Acid Test', value: 'Lactic Acid Test' },
  {
    label: 'Lactate Dehydrogenase (LDH) Test',
    value: 'Lactate Dehydrogenase (LDH) Test',
  },
  { label: 'Lipase Tests', value: 'Lipase Tests' },
  { label: 'Laparoscopy', value: 'Laparoscopy' },
  { label: 'Liver Function Tests', value: 'Liver Function Tests' },
  { label: 'Lipoprotein (a) Blood Test', value: 'Lipoprotein (a) Blood Test' },
  { label: 'Lung Function Tests', value: 'Lung Function Tests' },
  { label: 'Lung Cancer Tumor Markers', value: 'Lung Cancer Tumor Markers' },
  { label: 'Lyme Disease Tests', value: 'Lyme Disease Tests' },
  {
    label: 'Luteinizing Hormone (LH) Levels Test',
    value: 'Luteinizing Hormone (LH) Levels Test',
  },
  { label: 'Malaria Tests', value: 'Malaria Tests' },
  { label: 'Magnesium Blood Test', value: 'Magnesium Blood Test' },
  { label: 'Measles and Mumps Tests', value: 'Measles and Mumps Tests' },
  {
    label: 'MCV (Mean Corpuscular Volume)',
    value: 'MCV (Mean Corpuscular Volume)',
  },
  {
    label: 'Microalbumin Creatinine Ratio',
    value: 'Microalbumin Creatinine Ratio',
  },
  { label: 'Mental Health Screening', value: 'Mental Health Screening' },
  { label: 'MTHFR Mutation Test', value: 'MTHFR Mutation Test' },
  { label: 'MPV Blood Test', value: 'MPV Blood Test' },
  {
    label: 'Natriuretic Peptide Tests (BNP, NT-proBNP)',
    value: 'Natriuretic Peptide Tests (BNP, NT-proBNP)',
  },
  { label: 'Mucus in Urine', value: 'Mucus in Urine' },
  { label: 'Nitrites in Urine', value: 'Nitrites in Urine' },
  { label: 'Neurological Exam', value: 'Neurological Exam' },
  { label: 'Opioid Testing', value: 'Opioid Testing' },
  { label: 'Obesity Screening', value: 'Obesity Screening' },
  { label: 'Pap Smear', value: 'Pap Smear' },
  { label: 'Ova and Parasite Test', value: 'Ova and Parasite Test' },
  {
    label: 'Partial Thromboplastin Time (PTT) Test',
    value: 'Partial Thromboplastin Time (PTT) Test',
  },
  {
    label: 'Parathyroid Hormone (PTH) Test',
    value: 'Parathyroid Hormone (PTH) Test',
  },
  { label: 'Pharmacogenetic Tests', value: 'Pharmacogenetic Tests' },
  { label: 'PDL1 (Immunotherapy) Tests', value: 'PDL1 (Immunotherapy) Tests' },
  { label: 'Phosphate in Blood', value: 'Phosphate in Blood' },
  {
    label: 'Phenylketonuria (PKU) Screening',
    value: 'Phenylketonuria (PKU) Screening',
  },
  { label: 'Pleural Fluid Analysis', value: 'Pleural Fluid Analysis' },
  { label: 'Phosphate in Urine', value: 'Phosphate in Urine' },
  {
    label: 'Postpartum Depression Screening',
    value: 'Postpartum Depression Screening',
  },
  { label: 'Porphyrin Tests', value: 'Porphyrin Tests' },
  { label: 'Prealbumin Blood Test', value: 'Prealbumin Blood Test' },
  { label: 'Potassium Blood Test', value: 'Potassium Blood Test' },
  { label: 'Procalcitonin Test', value: 'Procalcitonin Test' },
  { label: 'Pregnancy Test', value: 'Pregnancy Test' },
  { label: 'Prolactin Levels', value: 'Prolactin Levels' },
  { label: 'Progesterone Test', value: 'Progesterone Test' },
  {
    label: 'Protein C and Protein S Tests',
    value: 'Protein C and Protein S Tests',
  },
  {
    label: 'Prostate-Specific Antigen (PSA) Test',
    value: 'Prostate-Specific Antigen (PSA) Test',
  },
  { label: 'PTEN Genetic Test', value: 'PTEN Genetic Test' },
  { label: 'Protein in Urine', value: 'Protein in Urine' },
  {
    label: 'Red Blood Cell Antibody Screen',
    value: 'Red Blood Cell Antibody Screen',
  },
  {
    label: 'RDW (Red Cell Distribution Width)',
    value: 'RDW (Red Cell Distribution Width)',
  },
  {
    label: 'Rheumatoid Factor (RF) Test',
    value: 'Rheumatoid Factor (RF) Test',
  },
  {
    label: 'Respiratory Syncytial Virus (RSV) Tests',
    value: 'Respiratory Syncytial Virus (RSV) Tests',
  },
  { label: 'SHBG Blood Test', value: 'SHBG Blood Test' },
  { label: 'Semen Analysis', value: 'Semen Analysis' },
  { label: 'Skin Cancer Screening', value: 'Skin Cancer Screening' },
  { label: 'Skin Biopsy', value: 'Skin Biopsy' },
  { label: 'Sodium Blood Test', value: 'Sodium Blood Test' },
  {
    label: 'Smooth Muscle Antibody (SMA) Test',
    value: 'Smooth Muscle Antibody (SMA) Test',
  },
  { label: 'Stool Elastase', value: 'Stool Elastase' },
  { label: 'Sonogram', value: 'Sonogram' },
  {
    label: 'Sweat Test for Cystic Fibrosis',
    value: 'Sweat Test for Cystic Fibrosis',
  },
  { label: 'Stress Tests', value: 'Stress Tests' },
  { label: 'Testosterone Levels Test', value: 'Testosterone Levels Test' },
  { label: 'Syphilis Tests', value: 'Syphilis Tests' },
  { label: 'Thyroid Antibodies', value: 'Thyroid Antibodies' },
  { label: 'Thyroglobulin', value: 'Thyroglobulin' },
  { label: 'TP53 Genetic Test', value: 'TP53 Genetic Test' },
  { label: 'Thyroxine (T4) Test', value: 'Thyroxine (T4) Test' },
  { label: 'Triglycerides Test', value: 'Triglycerides Test' },
  { label: 'Trichomoniasis Test', value: 'Trichomoniasis Test' },
  {
    label: 'TSH (Thyroid-stimulating hormone) Test',
    value: 'TSH (Thyroid-stimulating hormone) Test',
  },
  { label: 'Troponin Test', value: 'Troponin Test' },
  { label: 'Tumor Marker Tests', value: 'Tumor Marker Tests' },
  { label: 'Tuberculosis Screening', value: 'Tuberculosis Screening' },
  { label: 'Urobilinogen in Urine', value: 'Urobilinogen in Urine' },
  { label: 'Uric Acid Test', value: 'Uric Acid Test' },
  { label: 'Vision Screening', value: 'Vision Screening' },
  { label: 'Videonystagmography (VNG)', value: 'Videonystagmography (VNG)' },
  { label: 'Vitamin D Test', value: 'Vitamin D Test' },
  { label: 'Vitamin B Test', value: 'Vitamin B Test' },
  {
    label: 'White Blood Cell (WBC) in Stool',
    value: 'White Blood Cell (WBC) in Stool',
  },
  {
    label: 'Vitamin E (Tocopherol) Test',
    value: 'Vitamin E (Tocopherol) Test',
  },
  { label: 'Yeast Infection Tests', value: 'Yeast Infection Tests' },
  { label: 'Whooping Cough Diagnosis', value: 'Whooping Cough Diagnosis' },
  { label: 'Yeast Infection Tests', value: 'Yeast Infection Tests' },
  { label: 'Zika Virus Test', value: 'Zika Virus Test' },
  { label: '17-Hydroxyprogesterone', value: '17-Hydroxyprogesterone' },
];
